version: '3.8'

networks:
  spark-net:
    external: true

volumes:
  spark-vol:
    external: true

services:
  spark-master:
    image: bitnami/spark:latest
    networks:
      - spark-net
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    deploy:
      placement:
        constraints:
          - node.role == manager

  spark-worker:
    image: bitnami/spark:latest
    networks:
      - spark-net
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
    deploy:
      replicas: 3

  jupyter:
    image: jupyter/pyspark-notebook:latest
    networks:
      - spark-net
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=sparkdemo
    volumes:
      - spark-vol:/data
    deploy:
      placement:
        max_replicas_per_node: 1